{% set version = "1.1.2" %}
{% set sha256 = '5ccc7eb02edb82fafb8adbb90746af71460fbc29aa0f822526fc976dff83e93f' %}
{% set name = 'pyblake2' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  number: 1005
  script:
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - msinttypes  # [win and py<35]
    - pip
  run:
    - python

test:
  imports:
    - pyblake2
  commands:


about:
  home: https://github.com/dchest/pyblake2
  license_family: MIT
  license: MIT
  license_file: COPYING
  summary: |
    pyblake2 is an extension module for Python implementing BLAKE2 hash function.
    BLAKE2 is a cryptographic hash function, which offers highest security while being as fast as MD5 or SHA-1,

extra:
  recipe-maintainers:
    - mariusvniekerk
