{% set version = "1.1.1" %}
{% set sha256 = '8ec8e9087d13c99b354ab6d8b4cadb1758633db5946ff95a6bc7ac538b6d7b3d' %}
{% set name = 'pyblake2' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script:
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - toolchain
    - msinttypes  # [win and py<35]
    - pip
  run:
    - python

test:
  imports:
    - pyblake2
  commands:
    - conda inspect linkages {{ name|lower }}  # [unix]
    - conda inspect objects {{ name|lower }}   # [osx]


about:
  home: https://github.com/dchest/pyblake2
  license_family: MIT
  license: MIT
  license_file: COPYING
  summary: |
    pyblake2 is an extension module for Python implementing BLAKE2 hash function.
    BLAKE2 is a cryptographic hash function, which offers highest security while being as fast as MD5 or SHA-1,

extra:
  recipe-maintainers:
    - mariusvniekerk
