travis:
  secure:
    BINSTAR_TOKEN: YfJjP9HJ3Hw5f7Jb6hyVMU219wCrakU7hCnUG8QGrARZCKgk8gzMoAyK6EXAoJozh3DlQ6qKKOuHZH+LHsIPeVneAK95KQ3xVfpgejF/pyezJIgbNr0IdKehob8SJw57oqToM8AKehCQhIiFqoH/PI/R5+1WeHrmDWBWaqwM4B5eltR9O3o04G+q+XDy8EpTg1fb8cDAXfhAJjNOfcxWVoh4NvYUAv2+czNaZjHPR65jM/QkT412yNv9kPzEWaGN2hkRG9V6elfay6FbIoeWtRpxPjuN6Fv9BI0O0xkhuAAVil8lBDk9dI6JGcK5LCjxPSSuD5qGWigC2RYJhHuIe7R9uJUq5PtLn6nhxRwLSataVbGivnNYDvLs4J5xkxFLXMf9NJ/CrTOZvKBerq0u0tDawYacsIL3j6n66R0M14Yvrs+ZvkvUJNVNBDmAzEMP/KtTyBFNogKch7m5VmFa9FASS9lVc9UoaXwMcCTh2WBqA4rzQv3f0aTOvfCzNDbAIq86ILk2sqLeDo5aslMGJMhIkxEsUsa6UJsUs4HdpFR2Iiyu94KfEl7tLs64VzKg2aBdQJw5UEYT+MxtWD4spJW6lqYz78p0czGhl14MI6h31IojcTEqxmdNkIgmLVCZ44bJ+Fb499kvO1i5/4FGfhiGVoo83BjwyeQY4npuMeg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
